# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
      - main
      - test_unittest_github
      - 'test_unittest_github'
  pull_request:
    branches:
      - main
      - test_unittest_github
      - 'test_unittest_github'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.7"
    - name: Run tests
      run: python -m unittest test_taboo_cells.py
    - name: Run rodo tests
      run: |
        pip install pytest
        pytest test_unittest_github.py
